// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebForums.Data;

namespace WebForums.Migrations
{
    [DbContext(typeof(WebForumsContext))]
    [Migration("20210625162614_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebForums.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("WebForums.Models.Forum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Forum");
                });

            modelBuilder.Entity("WebForums.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PosterID")
                        .HasColumnType("int");

                    b.Property<int?>("ThreadID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("PosterID");

                    b.HasIndex("ThreadID");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("WebForums.Models.Thread", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ForumID")
                        .HasColumnType("int");

                    b.Property<int?>("StarterID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ForumID");

                    b.HasIndex("StarterID");

                    b.ToTable("Thread");
                });

            modelBuilder.Entity("WebForums.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebForums.Models.Forum", b =>
                {
                    b.HasOne("WebForums.Models.Category", "Category")
                        .WithMany("Forums")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebForums.Models.Post", b =>
                {
                    b.HasOne("WebForums.Models.User", "Poster")
                        .WithMany("Posts")
                        .HasForeignKey("PosterID");

                    b.HasOne("WebForums.Models.Thread", "Thread")
                        .WithMany("Posts")
                        .HasForeignKey("ThreadID");

                    b.Navigation("Poster");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("WebForums.Models.Thread", b =>
                {
                    b.HasOne("WebForums.Models.Forum", "Forum")
                        .WithMany("Threads")
                        .HasForeignKey("ForumID");

                    b.HasOne("WebForums.Models.User", "Starter")
                        .WithMany("Threads")
                        .HasForeignKey("StarterID");

                    b.Navigation("Forum");

                    b.Navigation("Starter");
                });

            modelBuilder.Entity("WebForums.Models.Category", b =>
                {
                    b.Navigation("Forums");
                });

            modelBuilder.Entity("WebForums.Models.Forum", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("WebForums.Models.Thread", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("WebForums.Models.User", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
